const tableData = [
  {
    "name":"魂魄 (Spirit)",
    "emf5":true,
    "orb":false,
    "box":true,
    "freezing":false,
    "fingerprints":false,
    "writing":true,
    "dots":false,
    "trait":"1. 點燃聖木 下次獵殺隔180秒",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"魅影 (Wraith)",
    "emf5":true,
    "orb":false,
    "box":true,
    "freezing":false,
    "fingerprints":false,
    "writing":false,
    "dots":true,
    "trait":"1. 不會踩鹽\n2. 離鬼房遠的時候 突然出現EMF 2 or 5 可能是魅影傳送到玩家旁邊",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"幻影 (Phantom)",
    "emf5":false,
    "orb":false,
    "box":true,
    "freezing":false,
    "fingerprints":true,
    "writing":false,
    "dots":true,
    "trait":"1. 獵殺時閃爍時間間隔長 \n2. 拍攝會進入隱身 沒有馬賽克\n3. 會隨機附身到玩家 出現EMF 2",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"騷靈 (Poltergeist)",
    "emf5":false,
    "orb":false,
    "box":true,
    "freezing":false,
    "fingerprints":true,
    "writing":true,
    "dots":false,
    "trait":"1. 同時大力丟多個物品",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"女妖 (Banshee)",
    "emf5":false,
    "orb":true,
    "box":false,
    "freezing":false,
    "fingerprints":true,
    "writing":false,
    "dots":true,
    "trait":"1. 獵殺時會鎖定目標\n2. 收音器有特殊尖叫\n3. 鬼魂事件常唱歌",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"巨靈 (Jinn)",
    "emf5":true,
    "orb":false,
    "box":false,
    "freezing":true,
    "fingerprints":true,
    "writing":false,
    "dots":false,
    "trait":"1. 不會關閉電閘",
    "speed":"打開電閘時 獵殺時看到玩家會大加速\n靠近目標會減到常速",
    "sanity":"50%"
  },
  {
    "name":"夢魘 (Mare)",
    "emf5":false,
    "orb":true,
    "box":true,
    "freezing":false,
    "fingerprints":false,
    "writing":true,
    "dots":false,
    "trait":"1. 不會主動開燈 \n2. 開燈時會瞬間關燈 \n3. 喜歡炸燈\n4. 不能開遙控器",
    "speed":"常速",
    "sanity":"燈打開 60%\n燈關掉 40%"
  },
  {
    "name":"亡魂 (Revenant)",
    "emf5":false,
    "orb":true,
    "box":false,
    "freezing":true,
    "fingerprints":false,
    "writing":true,
    "dots":false,
    "trait":null,
    "speed":"沒感知到玩家的時候較慢\n感知到玩家會加速 到達感知位置時會減速",
    "sanity":"50%"
  },
  {
    "name":"暗影 (Shade)",
    "emf5":true,
    "orb":false,
    "box":false,
    "freezing":true,
    "fingerprints":false,
    "writing":true,
    "dots":false,
    "trait":"1. 被召喚出來時 有機會是黑影\n2. 有人時幾乎不會互動",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"惡魔 (Demon)",
    "emf5":false,
    "orb":false,
    "box":false,
    "freezing":true,
    "fingerprints":true,
    "writing":true,
    "dots":false,
    "trait":"1. 有機率無視理智獵殺\n2. 獵殺冷卻時間20秒\n3. 點燃聖木 下次獵殺隔60秒",
    "speed":"常速",
    "sanity":"70%"
  },
  {
    "name":"幽靈 (Yurei)",
    "emf5":false,
    "orb":true,
    "box":false,
    "freezing":true,
    "fingerprints":false,
    "writing":false,
    "dots":true,
    "trait":"1. 點燃聖木 會約束幽靈在鬼房90秒\n2. 雙碰門 延遲關門 關大門",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"赤鬼 (Oni)",
    "emf5":true,
    "orb":false,
    "box":false,
    "freezing":true,
    "fingerprints":false,
    "writing":false,
    "dots":true,
    "trait":"1. 不會有鬼霧\n2. 獵殺時閃爍間隔短",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"妖怪 (Yokai)",
    "emf5":false,
    "orb":true,
    "box":true,
    "freezing":false,
    "fingerprints":false,
    "writing":false,
    "dots":true,
    "trait":"1. 通靈盒後有機會高理智獵殺\n2. 獵殺時難以被電子設備吸引",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"寒魔 (Hantu)",
    "emf5":false,
    "orb":true,
    "box":false,
    "freezing":true,
    "fingerprints":true,
    "writing":false,
    "dots":false,
    "trait":"1. 更喜歡關電閘 不會開電閘\n2. 關閉電閘時(or 3度以下) 獵殺會吐出寒氣\n3. 一定有刺骨寒溫",
    "speed":"熱的時候慢 冷的時候快",
    "sanity":"50%"
  },
  {
    "name":"御靈 (Goryo)",
    "emf5":true,
    "orb":false,
    "box":false,
    "freezing":false,
    "fingerprints":true,
    "writing":false,
    "dots":true,
    "trait":"1. 不會更換鬼房\n2. 只能用攝影機觀察的點陣\n3. 一定有點陣",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"鬼嬰 (Myling)",
    "emf5":true,
    "orb":false,
    "box":false,
    "freezing":false,
    "fingerprints":true,
    "writing":true,
    "dots":false,
    "trait":"1. 獵殺時聲音範圍小 電子設備被干擾之後才會聽到腳步聲\n2. 收音器更容易獲得回應",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"怨靈 (Onryo)",
    "emf5":false,
    "orb":true,
    "box":true,
    "freezing":true,
    "fingerprints":false,
    "writing":false,
    "dots":false,
    "trait":"1. 不會在火焰上獵殺\n2. 吹滅三次蠟燭會獵殺\n3. 可以跨房間熄滅蠟燭",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"攣魂 (Twins)",
    "emf5":true,
    "orb":false,
    "box":true,
    "freezing":true,
    "fingerprints":false,
    "writing":false,
    "dots":false,
    "trait":"1. 會遠距離兩個房間互動\n2. 副鬼會有EMF 5 其他沒有",
    "speed":"主鬼慢 副鬼快",
    "sanity":"50%"
  },
  {
    "name":"雷魂 (Raiju)",
    "emf5":true,
    "orb":true,
    "box":false,
    "freezing":false,
    "fingerprints":false,
    "writing":false,
    "dots":true,
    "trait":"1. 電子干擾更遠",
    "speed":"沒吸電視常速\n有電子設備會加速",
    "sanity":"50%"
  },
  {
    "name":"幻妖 (Obake)",
    "emf5":true,
    "orb":true,
    "box":false,
    "freezing":false,
    "fingerprints":true,
    "writing":false,
    "dots":false,
    "trait":"1. 獵殺時會變換形態\n2. 二燈 五監 五鍵 六門",
    "speed":"常速",
    "sanity":"50%"
  },
  {
    "name":"擬魂 (Mimic)",
    "emf5":false,
    "orb":true,
    "box":true,
    "freezing":true,
    "fingerprints":true,
    "writing":false,
    "dots":false,
    "trait":"1. 有假靈球證據",
    "speed":"不一定",
    "sanity":"不一定"
  },
  {
    "name":"魔洛伊 (Moroi)",
    "emf5":false,
    "orb":false,
    "box":true,
    "freezing":true,
    "fingerprints":false,
    "writing":true,
    "dots":false,
    "trait":"1. 會詛咒玩家2倍速掉理智\n2. 聖木致盲7.5秒",
    "speed":"裡至高速度慢 理智低速度快",
    "sanity":"50%"
  },
  {
    "name":"霧影 (Deogen)",
    "emf5":false,
    "orb":false,
    "box":true,
    "freezing":false,
    "fingerprints":false,
    "writing":true,
    "dots":true,
    "trait":"1. 會定位所有人 獵殺時 不能躲藏 只能溜鬼\n2. 通靈盒有機會得到特殊喘息\n3. 一定有通靈盒",
    "speed":"離玩家遠速度快 離玩家近速度超慢",
    "sanity":"40%"
  },
  {
    "name":"剎耶 (Thaye)",
    "emf5":false,
    "orb":true,
    "box":false,
    "freezing":false,
    "fingerprints":false,
    "writing":true,
    "dots":true,
    "trait":"1. 獵殺時不會因為看到玩家而加速",
    "speed":"年輕速度快 年老速度慢",
    "sanity":"75% - 15%"
  }
];